import React,{useEffect,useMemo,useState} from 'react';
import {api} from './api';
import {Modal,Search} from './StaffSettings';
import {CsvImportModal} from './CsvImportModal';
const statuses=[['PRESENT','Present'],['LATE','Late'],['ABSENT','Absent'],['EXCUSED','Excused']];
export function AttendanceManager({classes,students,run}){
 const [date,setDate]=useState(new Date().toISOString().slice(0,10)),[classId,setClassId]=useState(''),[records,setRecords]=useState([]),[marks,setMarks]=useState({}),[windows,setWindows]=useState([]),[open,setOpen]=useState(null),[query,setQuery]=useState('');
 const load=()=>Promise.all([api('/admin/attendance?date='+date).then(setRecords),api('/admin/attendance/windows?date='+date).then(setWindows)]);
 useEffect(()=>{load()},[date]);useEffect(()=>setMarks(Object.fromEntries(records.map(r=>[r.studentId,r.status]))),[records]);
 const shown=useMemo(()=>classId?students.filter(s=>s.classId===classId&&(!query||[s.name,s.email].some(v=>String(v||'').toLowerCase().includes(query.toLowerCase())))):[],[students,classId,query]);
 const attendanceWindow=windows.find(w=>w.classId===classId),classroom=classes.find(c=>c.id===classId),classRecords=records.filter(r=>students.find(s=>s.id===r.studentId)?.classId===classId),pending=classRecords.filter(r=>r.reviewStatus==='PENDING').length;
 const totals=Object.fromEntries(statuses.map(([key])=>[key,shown.filter(s=>marks[s.id]===key).length]));
 const save=()=>run(async()=>{const selected=shown.filter(s=>marks[s.id]);if(!selected.length)throw new Error('Mark at least one student');await api('/admin/attendance',{method:'POST',body:{date,records:selected.map(s=>({studentId:s.id,status:marks[s.id]}))}});await load()},'Attendance review saved');
 const activate=e=>{e.preventDefault();const d=new FormData(e.currentTarget);run(async()=>{await api('/admin/attendance/windows',{method:'POST',body:{classId,date,closesAt:new Date(`${date}T${d.get('closesAt')}`).toISOString()}});setOpen(null);await load()},'Student attendance marking activated')};
 const approve=()=>run(async()=>{await api('/admin/attendance/windows/'+attendanceWindow.id+'/approve',{method:'POST'});await load()},'Attendance reviewed and approved');
 return <div className="attendance-workspace">
  <section className="attendance-hero"><div><span className="eyebrow">DAILY REGISTER</span><h2>Attendance review</h2><p>Open student self-marking, review each response, make corrections and approve the final class register.</p></div><div className="attendance-summary">{statuses.map(([key,label])=><span key={key}><b>{totals[key]||0}</b>{label}</span>)}</div></section>
  <section className="panel attendance-controls"><label>Attendance date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Class register<select value={classId} onChange={e=>setClassId(e.target.value)}><option value="">Choose class</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><Search value={query} onChange={setQuery} placeholder="Search this class" count={shown.length}/><div className="attendance-control-actions"><button disabled={!classId} onClick={()=>setOpen('activate')}>{attendanceWindow?.status==='OPEN'?'Change closing time':'Open self-marking'}</button><button className="secondary" onClick={()=>setOpen('import')}>Import CSV</button></div></section>
  {classId?<><section className={'attendance-session '+String(attendanceWindow?.status||'STAFF').toLowerCase()}><div><span className="attendance-status-dot"/><div><strong>{attendanceWindow?.status==='OPEN'?'Student self-marking is open':attendanceWindow?.status==='APPROVED'?'Register approved':'Teacher marking mode'}</strong><small>{classroom?.name} · {new Date(date+'T00:00:00').toLocaleDateString()}{attendanceWindow?.closesAt?' · closes '+new Date(attendanceWindow.closesAt).toLocaleTimeString():''}</small></div></div><div><span className="badge">{pending} pending review</span>{attendanceWindow?.status==='OPEN'&&<button onClick={approve}>Approve register</button>}</div></section><section className="attendance-roster"><div className="attendance-roster-head"><div><h2>{classroom?.name} register</h2><p>{shown.length} students shown · select a status for each learner</p></div><button disabled={!shown.some(s=>marks[s.id])} onClick={save}>Save teacher review</button></div>{shown.map(s=>{const record=records.find(r=>r.studentId===s.id);return <article className="attendance-student" key={s.id}><div className="attendance-avatar">{s.profilePictureId?<img src={'/api/files/'+s.profilePictureId} alt=""/>:s.name[0]}</div><div className="attendance-name"><strong>{s.name}</strong><small>{s.email}</small></div><div className="attendance-options">{statuses.map(([key,label])=><button type="button" key={key} className={(marks[s.id]===key?'selected ':'')+key.toLowerCase()} onClick={()=>setMarks({...marks,[s.id]:key})}>{label}</button>)}</div><div className="attendance-review"><span>{record?.source==='STUDENT'?'Student entry':record?.source==='IMPORT'?'CSV import':record?'Teacher entry':'Not marked'}</span><small>{record?.reviewStatus==='PENDING'?'Needs review':record?.reviewStatus==='APPROVED'?'Reviewed':'—'}</small></div></article>})}{!shown.length&&<div className="rating-empty"><span>⌕</span><h2>No students found</h2><p>Adjust the search for this class.</p></div>}</section></>:<section className="panel rating-empty"><span>✓</span><h2>Choose a class register</h2><p>Select a class to review attendance and open student self-marking.</p></section>}
  <Modal title="Open student attendance marking" open={open==='activate'} onClose={()=>setOpen(null)}><form onSubmit={activate}><p>Students in <strong>{classroom?.name}</strong> can mark themselves present or late until the time below. Their entries stay pending until reviewed.</p><label>Closing time<input name="closesAt" type="time" defaultValue="09:00" required/></label><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setOpen(null)}>Cancel</button><button>Open attendance</button></div></form></Modal>
  <CsvImportModal type="attendance" open={open==='import'} onClose={()=>setOpen(null)} run={run} onComplete={load}/>
 </div>;
}