import React,{useEffect,useState} from 'react';
import {api} from './api';
import {Modal,Search} from './StaffSettings';

const emptyPage={items:[],page:1,pages:0,total:0};
export function Communications({user}){
 const [overview,setOverview]=useState(null),[campaigns,setCampaigns]=useState(emptyPage),[recipients,setRecipients]=useState(emptyPage),[selected,setSelected]=useState([]),[dialog,setDialog]=useState(null),[details,setDetails]=useState(null),[query,setQuery]=useState(''),[classFilter,setClassFilter]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const [o,c]=await Promise.all([api('/communications/overview'),api('/communications/campaigns?page=1&pageSize=25')]);setOverview(o);setCampaigns(c)}catch(e){setError(e.message)}finally{setLoading(false)}};
 const loadRecipients=async(page=1)=>{setLoading(true);setError('');try{setRecipients(await api(`/communications/recipients?page=${page}&pageSize=50&search=${encodeURIComponent(query)}${classFilter?`&classId=${encodeURIComponent(classFilter)}`:''}`))}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const act=async(fn,success)=>{setBusy(true);setError('');setMessage('');try{await fn();setMessage(success);await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const openComposer=()=>{setSelected([]);setRecipients(emptyPage);setQuery('');setClassFilter('');setDialog('compose')};
 const submit=e=>{e.preventDefault();const d=new FormData(e.currentTarget),audienceType=d.get('audienceType'),channels=d.getAll('channels');act(async()=>{await api('/communications/campaigns',{method:'POST',body:{audienceType,classId:d.get('classId')||null,studentIds:audienceType==='INDIVIDUAL'?selected:[],recipientType:d.get('recipientType'),channels,subject:d.get('subject'),body:d.get('body')}});setDialog(null)},'Message campaign queued for delivery')};
 const openDetails=async campaign=>{setBusy(true);setError('');try{setDetails({campaign,page:await api(`/communications/campaigns/${campaign.id}/recipients?page=1&pageSize=100`)});setDialog('details')}catch(e){setError(e.message)}finally{setBusy(false)}};
 if(loading&&!overview)return <div className="loading-panel">Loading communication services…</div>;
 return <div className="communications-page">{error&&<div className="error" role="alert">{error}</div>}{message&&<div className="success" role="status">{message}</div>}
  <section className="communication-hero"><div><span className="eyebrow">SCHOOL COMMUNICATIONS</span><h2>Email and SMS centre</h2><p>Send operational messages to an individual learner, guardians, one class, or the whole school.</p></div><button onClick={openComposer}>+ Compose message</button></section>
  <div className="dashboard-stats"><article className="dashboard-stat"><span>Campaigns</span><strong>{overview?.counts.campaigns||0}</strong><small>Recorded sends</small></article><article className="dashboard-stat"><span>Waiting</span><strong>{overview?.counts.queued||0}</strong><small>Queued or processing</small></article><article className="dashboard-stat"><span>Failed</span><strong>{overview?.counts.failed||0}</strong><small>Need review</small></article></div>
  <section className="panel provider-status"><div><span className={overview?.capabilities.email.configured?'dot':'dot amber'}/><strong>Email</strong><small>{overview?.capabilities.email.enabled?(overview.capabilities.email.configured?'Ready':'Provider not configured'):'Disabled in feature settings'}</small></div><div><span className={overview?.capabilities.sms.configured?'dot':'dot amber'}/><strong>SMS</strong><small>{overview?.capabilities.sms.enabled?(overview.capabilities.sms.configured?'Ready':'Provider not configured'):'Disabled in feature settings'}</small></div></section>
  <section className="panel table-wrap"><div className="panel-title"><div><span className="eyebrow">DELIVERY HISTORY</span><h2>Message campaigns</h2></div><button className="secondary" onClick={load} disabled={loading}>Refresh</button></div><table><thead><tr><th>Message</th><th>Audience</th><th>Delivery</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody>{campaigns.items.map(c=><tr key={c.id}><td><strong>{c.subject||'SMS message'}</strong><small>{c.body.slice(0,90)}{c.body.length>90?'…':''}</small></td><td>{c.class?.name||c.audienceType.toLowerCase()}<small>{c.recipientCount} destinations · {c.recipientType.toLowerCase()}</small></td><td>{Object.entries(c.delivery).map(([status,count])=><span className="delivery-count" key={status}>{status.toLowerCase()}: {count}</span>)}</td><td><span className={'badge '+c.status.toLowerCase()}>{c.status.toLowerCase()}</span></td><td>{new Date(c.createdAt).toLocaleString()}<small>by {c.sender.name}</small></td><td className="row-actions"><button className="text-button" onClick={()=>openDetails(c)}>View delivery</button>{['QUEUED','SENDING'].includes(c.status)&&<button className="text-button" disabled={busy} onClick={()=>act(()=>api(`/communications/campaigns/${c.id}/cancel`,{method:'POST'}),'Queued deliveries cancelled')}>Cancel</button>}{['FAILED','PARTIAL'].includes(c.status)&&<button className="text-button" disabled={busy} onClick={()=>act(()=>api(`/communications/campaigns/${c.id}/retry`,{method:'POST'}),'Failed deliveries queued again')}>Retry failed</button>}</td></tr>)}</tbody></table>{!campaigns.items.length&&<p className="empty">No messages have been queued yet.</p>}</section>
  <Modal title="Compose email or SMS" open={dialog==='compose'} onClose={()=>setDialog(null)} wide><form onSubmit={submit} className="communication-form"><div className="form-grid"><label>Audience<select name="audienceType" defaultValue="CLASS" onChange={e=>{if(e.target.value==='INDIVIDUAL')loadRecipients();}}><option value="INDIVIDUAL">Selected students</option><option value="CLASS">One class</option>{user?.role==='ADMIN'&&<option value="ALL">All active students</option>}</select></label><label>Class<select name="classId" onChange={e=>setClassFilter(e.target.value)}><option value="">Choose when sending to a class</option>{overview?.classes.map(c=><option value={c.id} key={c.id}>{c.name} · {c._count.students} students</option>)}</select></label><label>Recipients<select name="recipientType" defaultValue="GUARDIAN"><option value="STUDENT">Students</option><option value="GUARDIAN">Guardians</option><option value="BOTH">Students and guardians</option></select></label><fieldset><legend>Delivery channels</legend><label className="check"><input type="checkbox" name="channels" value="EMAIL" disabled={!overview?.capabilities.email.enabled||!overview?.capabilities.email.configured}/>Email</label><label className="check"><input type="checkbox" name="channels" value="SMS" disabled={!overview?.capabilities.sms.enabled||!overview?.capabilities.sms.configured}/>SMS</label></fieldset><label>Email subject<input name="subject" maxLength="200" placeholder="Required when email is selected"/></label><label className="message-body">Message<textarea name="body" required maxLength="20000" rows="8"/></label></div><section className="recipient-picker"><div className="panel-title"><div><strong>Individual recipients</strong><small>Used only when “Selected students” is chosen.</small></div><span className="badge">{selected.length} selected</span></div><div className="toolbar"><Search value={query} onChange={setQuery} placeholder="Search students or guardians"/><button type="button" className="secondary" onClick={()=>loadRecipients()}>Find</button></div><div className="recipient-checks">{recipients.items.map(student=><label className="check" key={student.id}><input type="checkbox" checked={selected.includes(student.id)} onChange={e=>setSelected(e.target.checked?[...selected,student.id]:selected.filter(id=>id!==student.id))}/><span><strong>{student.name}</strong><small>{student.class?.name||'No class'} · guardian: {student.emergencyContactName||'not recorded'} · student email {student.studentEmailAvailable?'available':'missing'} · student SMS {student.studentSmsAvailable?'available':'missing'} · guardian email {student.guardianEmailAvailable?'available':'missing'} · guardian SMS {student.guardianSmsAvailable?'available':'missing'}</small></span></label>)}</div></section><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setDialog(null)}>Cancel</button><button disabled={busy}>Queue message</button></div></form></Modal>
  <Modal title="Delivery details" open={dialog==='details'} onClose={()=>setDialog(null)} wide>{details&&<section className="table-wrap"><h3>{details.campaign.subject||'SMS message'}</h3><table><thead><tr><th>Recipient</th><th>Channel</th><th>Destination</th><th>Status</th><th>Attempts</th><th>Details</th></tr></thead><tbody>{details.page.items.map(row=><tr key={row.id}><td>{row.recipientName}<small>{row.student.name} · {row.student.class?.name||'No class'}</small></td><td>{row.channel}</td><td>{row.destination}</td><td><span className={'badge '+row.status.toLowerCase()}>{row.status.toLowerCase()}</span></td><td>{row.attempts}</td><td>{row.sentAt?new Date(row.sentAt).toLocaleString():row.lastError||'Waiting'}</td></tr>)}</tbody></table></section>}</Modal>
 </div>;
}
