import React,{useState} from 'react';
import {api,downloadCsv} from './api';
import {Modal} from './StaffSettings';

const definitions={
 students:{title:'Import students',path:'/admin/students/import',headers:['name','email','password','className','phone','address','dateOfBirth','gender','emergencyContactName','emergencyContactPhone','emergencyRelationship','guardianEmail','studentAllowEmail','studentAllowSms','guardianAllowEmail','guardianAllowSms','medicalInformation'],sample:['Ada Student','ada@example.test','TemporaryPass123!','JSS1','','','2012-04-10','Female','Ada Guardian','+2348000000000','Parent','guardian@example.test','true','true','true','true','']},
 staff:{title:'Import staff',path:'/admin/staff/import',headers:['name','email','password','roleName','employeeNumber','phone','address','qualifications','classNames'],sample:['Mary Teacher','mary@example.test','TemporaryPass123!','Teacher','EMP-100','','','B.Ed|TRCN','JSS1|JSS2']},
 attendance:{title:'Import attendance',path:'/admin/attendance/import',headers:['studentEmail','date','status'],sample:['ada@example.test',new Date().toISOString().slice(0,10),'PRESENT']},
 results:{title:'Import results',path:'/admin/results/import',headers:['studentEmail','termId','subjectCode','componentKey','title','score','maxScore','comment'],sample:['ada@example.test','paste-term-id','MTH','FINAL_EXAM','Imported examination','72','100','']}
};
function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i],next=text[i+1];if(c==='"'&&quoted&&next==='"'){cell+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&next==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell='';}else cell+=c;}row.push(cell);if(row.some(v=>v.trim()))rows.push(row);if(rows.length<2)throw new Error('The CSV must contain a header row and at least one record');const headers=rows[0].map((h,i)=>(i===0?h.replace(/^\uFEFF/,''):h).trim());return rows.slice(1).map(values=>Object.fromEntries(headers.map((h,i)=>[h,(values[i]||'').trim()])));}
export function CsvImportModal({type,open,onClose,run,onComplete}){const def=definitions[type], [file,setFile]=useState(null),[result,setResult]=useState(null);if(!def)return null;const submit=e=>{e.preventDefault();run(async()=>{if(!file)throw new Error('Choose a CSV file');const rows=parseCsv(await file.text());const response=await api(def.path,{method:'POST',body:{rows}});setResult(response);await onComplete?.()},`${def.title}: import finished`)};return <Modal title={def.title} open={open} onClose={()=>{setResult(null);setFile(null);onClose()}} wide><form onSubmit={submit}><p className="muted">Download the template, keep its header names, then upload up to 2,000 rows. Valid rows are saved and invalid rows are listed.</p><div className="import-drop"><input type="file" accept=".csv,text/csv" onChange={e=>setFile(e.target.files[0]||null)} required/><button type="button" className="secondary" onClick={()=>downloadCsv(`${type}-import-template.csv`,[def.headers,def.sample])}>Download CSV template</button></div>{result&&<div className={result.failed?'import-result warning':'import-result success'}><strong>{result.imported} of {result.total} rows imported</strong>{result.failed>0&&<><p>{result.failed} rows need correction.</p><div className="import-errors">{result.errors.map((x,i)=><small key={i}>Row {x.row}: {x.error}</small>)}</div></>}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Close</button><button>Validate and import</button></div></form></Modal>}
