import React,{useEffect,useMemo,useState} from 'react';
import {api} from './api';
import {Modal,Search} from './StaffSettings';

const Field=({title,children})=><label>{title}{children}</label>;
const genderLabel=value=>value==='MALE'?'Male students':value==='FEMALE'?'Female students':'Mixed';
export function HostelManagement(){
  const [data,setData]=useState({hostels:[],allocations:[],students:[],summary:{hostels:0,rooms:0,beds:0,occupied:0,available:0}});
  const [query,setQuery]=useState(''),[dialog,setDialog]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  const load=async()=>setData(await api('/hostels/dashboard'));
  useEffect(()=>{load().catch(e=>setError(e.message))},[]);
  const perform=async(fn,success)=>{setBusy(true);setError('');setMessage('');try{await fn();await load();setDialog(null);setMessage(success)}catch(e){setError(e.message)}finally{setBusy(false)}};
  const allocatedIds=new Set(data.allocations.map(x=>x.studentId));
  const eligible=data.students.filter(s=>!allocatedIds.has(s.id));
  const beds=useMemo(()=>data.hostels.flatMap(h=>h.active?h.rooms.flatMap(r=>r.active?r.beds.filter(b=>b.active&&!b.allocations.length).map(b=>({id:b.id,label:`${h.name} · ${r.name} · ${b.label}`})):[]):[]),[data.hostels]);
  const q=query.trim().toLowerCase();
  const allocations=data.allocations.filter(x=>!q||[x.student.name,x.student.email,x.student.class?.name,x.bed.room.hostel.name,x.bed.room.name,x.bed.label].some(v=>String(v||'').toLowerCase().includes(q)));
  const createHostel=e=>{e.preventDefault();const d=new FormData(e.currentTarget);perform(()=>api('/hostels',{method:'POST',body:{name:d.get('name'),genderPolicy:d.get('genderPolicy'),address:d.get('address')}}),'Hostel created')};
  const createRoom=e=>{e.preventDefault();const d=new FormData(e.currentTarget);perform(()=>api(`/hostels/${d.get('hostelId')}/rooms`,{method:'POST',body:{name:d.get('name'),floor:d.get('floor'),capacity:Number(d.get('capacity')),bedPrefix:d.get('bedPrefix')}}),'Room and bed spaces created')};
  const allocate=e=>{e.preventDefault();const d=new FormData(e.currentTarget),startsAt=d.get('startsAt');perform(()=>api('/hostels/allocations',{method:'POST',body:{studentId:d.get('studentId'),bedId:d.get('bedId'),...(startsAt?{startsAt:new Date(startsAt).toISOString()}:{}),notes:d.get('notes')}}),'Student allocated to hostel')};
  return <div className="hostel-workspace">
    <section className="hostel-hero"><div><span className="eyebrow">BOARDING OPERATIONS</span><h2>Hostel management</h2><p>Manage buildings, rooms, bed spaces and current student residents from one workspace.</p></div><div className="hostel-hero-count"><strong>{data.summary.available}</strong><span>bed spaces available</span></div></section>
    {error&&<div className="error" role="alert">{error}</div>}{message&&<div className="success" role="status">{message}</div>}
    <div className="dashboard-stats">{[['Hostels',data.summary.hostels],['Rooms',data.summary.rooms],['Bed spaces',data.summary.beds],['Occupied',data.summary.occupied]].map(([label,value])=><article className="dashboard-stat static" key={label}><span>{label}</span><strong>{value}</strong></article>)}</div>
    <div className="toolbar hostel-toolbar"><Search value={query} onChange={setQuery} placeholder="Search residents, class or hostel" count={allocations.length}/><div className="toolbar-actions"><button onClick={()=>setDialog('hostel')}>+ Add hostel</button><button className="secondary" disabled={!data.hostels.some(h=>h.active)} onClick={()=>setDialog('room')}>+ Add room</button><button className="secondary" disabled={!eligible.length||!beds.length} onClick={()=>setDialog('allocation')}>Allocate student</button></div></div>
    <div className="hostel-grid">{data.hostels.map(hostel=>{const total=hostel.rooms.reduce((n,r)=>n+r.beds.filter(b=>b.active).length,0),occupied=hostel.rooms.reduce((n,r)=>n+r.beds.filter(b=>b.allocations.length).length,0);return <section className={'panel hostel-card '+(!hostel.active?'inactive':'')} key={hostel.id}><div className="panel-title"><div><span className="badge">{genderLabel(hostel.genderPolicy)}</span><h2>{hostel.name}</h2><p>{hostel.address||'Address not entered'}</p></div><button className="text-button" disabled={busy} onClick={()=>perform(()=>api('/hostels/'+hostel.id,{method:'PATCH',body:{active:!hostel.active}}),hostel.active?'Hostel disabled':'Hostel enabled')}>{hostel.active?'Disable':'Enable'}</button></div><div className="occupancy-line"><span style={{width:`${total?Math.round(occupied/total*100):0}%`}}/></div><small>{occupied} of {total} bed spaces occupied</small><div className="hostel-rooms">{hostel.rooms.map(room=><article key={room.id}><div><strong>{room.name}</strong><small>{room.floor||'Floor not specified'} · {room.beds.filter(b=>b.allocations.length).length}/{room.beds.length} occupied</small></div><span className={room.active?'badge':'badge muted'}>{room.active?'Open':'Closed'}</span></article>)}{!hostel.rooms.length&&<p className="empty">No rooms have been added.</p>}</div></section>})}</div>
    {!data.hostels.length&&<section className="panel empty hostel-empty"><span>⌂</span><h2>Add your first hostel</h2><p>Create a hostel building, then add rooms and allocate students to bed spaces.</p></section>}
    <section className="panel table-wrap"><div className="panel-title"><div><span className="eyebrow">CURRENT RESIDENTS</span><h2>Active allocations</h2></div><span className="muted">{allocations.length} shown</span></div><table><thead><tr><th>Student</th><th>Class</th><th>Hostel and room</th><th>Check-in</th><th>Action</th></tr></thead><tbody>{allocations.map(row=><tr key={row.id}><td><strong>{row.student.name}</strong><small>{row.student.email}</small></td><td>{row.student.class?.name||'Unassigned'}</td><td>{row.bed.room.hostel.name}<small>{row.bed.room.name} · Bed {row.bed.label}</small></td><td>{new Date(row.startsAt).toLocaleDateString()}</td><td><button className="text-button" onClick={()=>setDialog({type:'checkout',allocation:row})}>Check out</button></td></tr>)}</tbody></table>{!allocations.length&&<p className="empty">No active hostel residents match this view.</p>}</section>

    <Modal title="Add hostel" open={dialog==='hostel'} onClose={()=>setDialog(null)}><form onSubmit={createHostel}><Field title="Hostel name"><input name="name" required maxLength="150" placeholder="e.g. Unity House"/></Field><Field title="Student group"><select name="genderPolicy" defaultValue="MIXED"><option value="MIXED">Mixed</option><option value="MALE">Male students</option><option value="FEMALE">Female students</option></select></Field><Field title="Address or location"><textarea name="address" maxLength="500"/></Field><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setDialog(null)}>Cancel</button><button disabled={busy}>Create hostel</button></div></form></Modal>
    <Modal title="Add room and bed spaces" open={dialog==='room'} onClose={()=>setDialog(null)}><form onSubmit={createRoom}><Field title="Hostel"><select name="hostelId" required><option value="">Select hostel</option>{data.hostels.filter(h=>h.active).map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select></Field><div className="form-grid"><Field title="Room name or number"><input name="name" required maxLength="100" placeholder="Room 101"/></Field><Field title="Floor"><input name="floor" maxLength="50" placeholder="Ground floor"/></Field><Field title="Number of bed spaces"><input name="capacity" type="number" min="1" max="100" defaultValue="4" required/></Field><Field title="Bed label prefix"><input name="bedPrefix" maxLength="12" defaultValue="B" required/></Field></div><p className="muted">Bed labels are created automatically, for example B01, B02 and B03.</p><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setDialog(null)}>Cancel</button><button disabled={busy}>Add room</button></div></form></Modal>
    <Modal title="Allocate student" open={dialog==='allocation'} onClose={()=>setDialog(null)}><form onSubmit={allocate}><Field title="Student"><select name="studentId" required><option value="">Select student</option>{eligible.map(s=><option key={s.id} value={s.id}>{s.name} · {s.class?.name||'No class'}</option>)}</select></Field><Field title="Available bed space"><select name="bedId" required><option value="">Select bed</option>{beds.map(b=><option key={b.id} value={b.id}>{b.label}</option>)}</select></Field><Field title="Check-in date and time"><input name="startsAt" type="datetime-local"/></Field><Field title="Notes"><textarea name="notes" maxLength="1000" placeholder="Optional allocation notes"/></Field><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setDialog(null)}>Cancel</button><button disabled={busy}>Allocate student</button></div></form></Modal>
    <Modal title="Check student out" open={dialog?.type==='checkout'} onClose={()=>setDialog(null)}><p>Close the hostel allocation for <strong>{dialog?.allocation?.student.name}</strong> in {dialog?.allocation?.bed.room.hostel.name}?</p><div className="modal-actions"><button className="secondary" onClick={()=>setDialog(null)}>Cancel</button><button disabled={busy} onClick={()=>perform(()=>api('/hostels/allocations/'+dialog.allocation.id,{method:'PATCH',body:{status:'CHECKED_OUT'}}),'Student checked out')}>Check out student</button></div></Modal>
  </div>;
}