import React,{useEffect,useState} from 'react';
import {api,uploadFile} from './api';
import {Modal,Search} from './StaffSettings';

export function Library({user,run}){
 const [items,setItems]=useState([]),[catalog,setCatalog]=useState({courses:[],subjects:[]}),[query,setQuery]=useState(''),[open,setOpen]=useState(false),[viewer,setViewer]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const canUpload=user.role==='ADMIN'||user.permissions?.includes('LIBRARY_MANAGE');
 const load=async()=>{setLoading(true);setError('');try{const [rows,cat]=await Promise.all([api('/academics/library'),api('/academics/catalog')]);setItems(rows);setCatalog(cat)}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const submit=e=>{e.preventDefault();const form=e.currentTarget,d=new FormData(form);run(async()=>{const file=await uploadFile(d.get('file'),'library');await api('/academics/library',{method:'POST',body:{title:d.get('title'),author:d.get('author'),category:d.get('category'),description:d.get('description'),fileId:file.id,classId:d.get('classId')||null,subjectId:d.get('subjectId')||null,published:d.get('published')==='on'}});form.reset();setOpen(false);await load()},'Library material uploaded')};
 const shown=items.filter(x=>!query||[x.title,x.author,x.category,x.description,x.class?.name,x.subject?.name].some(v=>String(v||'').toLowerCase().includes(query.toLowerCase())));
 return <><div className="toolbar"><Search value={query} onChange={setQuery} placeholder="Search title, author or subject"/>{canUpload&&<button onClick={()=>setOpen(true)}>+ Upload material</button>}</div>{error&&<div className="error" role="alert">{error}<button className="secondary" onClick={load}>Try again</button></div>}{loading?<div className="panel loading-panel">Loading library…</div>:<div className="library-grid">{shown.map(x=><article className="panel library-card" key={x.id}><span className="class-symbol">▥</span><div><span className="badge">{x.category||'Library'}</span><h2>{x.title}</h2><p>{x.description||'No description supplied.'}</p><small>{x.author&&('By '+x.author+' · ')}{x.class?.name||'All classes'}{x.subject?.name&&(' · '+x.subject.name)}<br/>{x.file.originalName} · uploaded by {x.uploadedBy.name}</small></div>{x.file.mimeType==='application/pdf'?<button onClick={()=>setViewer(x)}>View PDF</button>:<a className="button-link" target="_blank" rel="noopener noreferrer" href={'/api/files/'+x.fileId}>Open material</a>}</article>)}</div>}{!loading&&!shown.length&&<p className="empty panel">No library materials match this search.</p>}
 <Modal title="Upload library material" open={open} onClose={()=>setOpen(false)} wide><form className="form-grid" onSubmit={submit}><label>Title<input name="title" required maxLength="200"/></label><label>Author<input name="author" maxLength="150"/></label><label>Category<input name="category" placeholder="Textbook, notes, reference…" maxLength="100"/></label><label>File<input name="file" type="file" accept=".pdf,.png,.jpg,.jpeg,.txt" required/></label><label>Class<select name="classId"><option value="">All permitted classes</option>{[...new Map(catalog.courses.map(c=>[c.class.id,c.class])).values()].map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Subject<select name="subjectId"><option value="">All permitted subjects</option>{catalog.subjects.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label className="span-2">Description<textarea name="description" maxLength="5000"/></label><label className="check"><input name="published" type="checkbox" defaultChecked/>Visible to students</label><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button>Upload material</button></div></form></Modal>
 <Modal title={viewer?.title||'Library PDF'} open={!!viewer} onClose={()=>setViewer(null)} wide><div className="pdf-viewer" onContextMenu={e=>e.preventDefault()}><div className="pdf-viewer-note"><span>View-only library document</span><small>Use the page controls to read the material.</small></div>{viewer&&<iframe title={viewer.title} src={'/api/files/'+viewer.fileId+'#toolbar=0&navpanes=0&scrollbar=1'}/>}</div></Modal></>;
}
export function AuditLogPage(){
 const [data,setData]=useState({items:[],page:1,pages:1,total:0}),[query,setQuery]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const load=async(page=1,search=query)=>{setLoading(true);setError('');try{setData(await api(`/admin/audit?page=${page}&pageSize=50&search=${encodeURIComponent(search)}`))}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load(1,'')},[]);
 const search=e=>{e.preventDefault();load(1,query)};
 return <><form className="toolbar" onSubmit={search}><Search value={query} onChange={setQuery} placeholder="Search action or record ID"/><button>Search logs</button></form>{error&&<div className="error" role="alert">{error}</div>}<section className="panel table-wrap"><div className="panel-title"><h2>Access and change log</h2><span className="badge">{data.total} events</span></div>{loading?<p className="empty">Loading activity…</p>:<table><thead><tr><th>Action</th><th>Account</th><th>Record</th><th>When</th></tr></thead><tbody>{data.items.map(log=><tr key={log.id}><td><strong>{log.action.replaceAll('.',' ')}</strong></td><td>{log.actor?.name||'Unknown account'}<small>{log.actor?.email||log.actorId}</small></td><td>{log.entityId}</td><td>{new Date(log.createdAt).toLocaleString()}</td></tr>)}</tbody></table>}<div className="pagination"><button className="secondary" disabled={loading||data.page<=1} onClick={()=>load(data.page-1)}>← Previous</button><span>Page {data.page} of {Math.max(data.pages,1)}</span><button className="secondary" disabled={loading||data.page>=data.pages} onClick={()=>load(data.page+1)}>Next →</button></div></section></>;
}
