import React,{useEffect,useState} from 'react';
import {api,setCsrf} from './api';
const money=n=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(n/100);
export function PlatformAdmin(){const [admin,setAdmin]=useState(null),[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
  useEffect(()=>{api('/platform/me').then(x=>{setAdmin(x.admin);setCsrf(x.csrf);return api('/platform/dashboard')}).then(setData).catch(()=>{}).finally(()=>setLoading(false))},[]);
  async function login(e){e.preventDefault();setError('');try{const x=await api('/platform/login',{method:'POST',body:Object.fromEntries(new FormData(e.currentTarget))});setAdmin(x.admin);setCsrf(x.csrf);setData(await api('/platform/dashboard'))}catch(x){setError(x.message)}}
  async function logout(){await api('/platform/logout',{method:'POST'});setCsrf('');setAdmin(null);setData(null)}
  if(loading)return <div className="platform-loading"><i className="spinner"/>Opening command centre</div>;
  if(!admin)return <main className="platform-login"><section><div className="platform-logo">S</div><span className="eyebrow">SCHOOLHOUSE PLATFORM</span><h1>Command centre</h1><p>Restricted access for platform operations and subscription oversight.</p><form onSubmit={login}><label>Platform email<input name="email" type="email" defaultValue="admin@techinvasion.com.ng" required/></label><label>Password<input name="password" type="password" autoComplete="current-password" required/></label><button className="primary wide">Open dashboard</button>{error&&<p className="error">{error}</p>}</form><a href="/">← Return to Schoolhouse</a></section></main>;
  const m=data?.metrics||{};return <main className="platform"><aside><div className="platform-logo">S</div><strong>Schoolhouse</strong><span>Platform operations</span><nav><b>Overview</b><span>Schools</span><span>Subscriptions</span><span>System health</span></nav><button onClick={logout}>Sign out</button></aside><section className="platform-main"><header><div><span className="eyebrow">PLATFORM OVERVIEW</span><h1>Good day, {admin.name}.</h1><p>Live commercial and tenant activity across Schoolhouse.</p></div><div className="admin-chip">PA</div></header><div className="metric-grid"><article><span>Schools</span><strong>{m.organizations||0}</strong><small>Total workspaces</small></article><article><span>Trials</span><strong>{m.activeTrials||0}</strong><small>Seven-day evaluations</small></article><article><span>Subscribers</span><strong>{m.activeSubscriptions||0}</strong><small>Active paid plans</small></article><article><span>Monthly run rate</span><strong>{money(m.monthlyRevenueMinor||0)}</strong><small>Current subscriptions</small></article></div><section className="tenant-table"><div className="table-title"><div><h2>School workspaces</h2><p>Latest tenant, plan and account activity.</p></div><span>{m.totalUsers||0} users</span></div><div className="table-scroll"><table><thead><tr><th>School</th><th>Package</th><th>Status</th><th>Users</th><th>Trial / renewal</th><th>Joined</th></tr></thead><tbody>{(data?.organizations||[]).map(o=><tr key={o.id}><td><b>{o.name}</b><small>{o.slug}</small></td><td>{o.subscription?.plan?.name||'Legacy'}</td><td><span className={`status-pill ${(o.subscription?.status||'active').toLowerCase()}`}>{o.subscription?.status||'ACTIVE'}</span></td><td>{o.userCount}</td><td>{new Date(o.subscription?.nextChargeAt||o.trialEndsAt||o.createdAt).toLocaleDateString()}</td><td>{new Date(o.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table></div></section></section></main>}
