import React,{useEffect,useMemo,useRef,useState} from 'react';
import {api} from './api';
import {Modal} from './StaffSettings';
import {BrandImage,OptionalImage} from './BrandImage';
import {printElement} from './print';

export const reportTemplates=[
 {key:'CLASSIC',name:'Schoolhouse classic',description:'Clean landscape report with ranks and averages'},
 {key:'NURSERY_SKILLS',name:'Nursery skills',description:'Purple developmental layout inspired by the nursery sample'},
 {key:'TERM_PORTRAIT',name:'Term portrait',description:'Yellow portrait layout with conduct panels'},
 {key:'MIDTERM_COMPACT',name:'Mid-term compact',description:'Warm compact assessment and grade analysis layout'},
 {key:'GRID_SHEET',name:'Grid sheet',description:'Blue structured continuous-assessment sheet'},
 {key:'COLLEGE_TERM',name:'College term',description:'Formal grey term report with conduct ratings'}
];
const affective={attentiveness:'Attentiveness',honesty:'Honesty',neatness:'Neatness',politeness:'Politeness',punctuality:'Punctuality / assembly',selfControl:'Self control / calmness',obedience:'Obedience',reliability:'Reliability',responsibility:'Sense of responsibility',relationshipWithOthers:'Relationship with others'};
const psychomotor={handlingOfTools:'Handling of tools',drawingPainting:'Drawing / painting',handwriting:'Handwriting',publicSpeaking:'Public speaking',speechFluency:'Speech fluency',sportsAndGames:'Sports and games'};
const extraActivities={sports:'Sports',leadership:'Leadership',teamwork:'Teamwork',creativity:'Creative activities',music:'Music',clubs:'Clubs / societies',communityService:'Community service'};
const metadataFields={admissionNumber:'Admission number',gender:'Gender',dateOfBirth:'Date of birth',age:'Age',house:'House',clubSociety:'Club / society',heightCm:'Height (cm)',weightKg:'Weight (kg)',nextTermBegins:'Next term begins',promotionStatus:'Promotion status',teacherName:'Class teacher'};
const defaults={templateKey:'CLASSIC',teacherComment:'',principalComment:'',affectiveRatings:{},psychomotorRatings:{},reportMetadata:{},published:false};
const titleCase=value=>String(value||'').replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());

function RatingTable({title,items,values}){return <table className="conduct-table"><thead><tr><th>{title}</th>{[5,4,3,2,1].map(n=><th key={n}>{n}</th>)}</tr></thead><tbody>{Object.entries(items).map(([key,label])=><tr key={key}><td>{label}</td>{[5,4,3,2,1].map(n=><td key={n}>{values[key]===n?'✓':''}</td>)}</tr>)}</tbody></table>}

export default function ReportCard({report,run,editable=true}){
 const [settings,setSettings]=useState({...defaults,...report.reportSettings}),[open,setOpen]=useState(false),printRef=useRef(null);
 useEffect(()=>setSettings({...defaults,...report.reportSettings}),[report]);
 const componentKeys=useMemo(()=>[...new Set(report.subjects.flatMap(s=>s.entries.map(e=>e.componentKey)))],[report]);
 const template=reportTemplates.find(x=>x.key===settings.templateKey)||reportTemplates[0],meta=settings.reportMetadata||{},extra=report.ratings?.find(x=>x.category==='EXTRA_CURRICULAR')?.ratings||{};
 const save=e=>{e.preventDefault();const d=new FormData(e.currentTarget),next={templateKey:d.get('templateKey'),teacherComment:d.get('teacherComment'),principalComment:d.get('principalComment'),published:d.get('published')==='on',reportMetadata:Object.fromEntries(Object.keys(metadataFields).map(k=>[k,String(d.get(k)||'')])),affectiveRatings:Object.fromEntries(Object.keys(affective).map(k=>[k,Number(d.get('affective_'+k)||1)])),psychomotorRatings:Object.fromEntries(Object.keys(psychomotor).map(k=>[k,Number(d.get('psychomotor_'+k)||1)]))};run(async()=>{await api(`/academics/reports/${report.student.id}/${report.term.id}/comments`,{method:'PUT',body:next});setSettings(next);setOpen(false)},'Report card settings saved')};
 return <>
  <article ref={printRef} className={`report-card report-template-${settings.templateKey.toLowerCase()} panel`} style={{'--watermark':report.school.watermarkPath?`url(/api/assets/${report.school.watermarkPath})`:'none'}}>
   <div className="report-actions">{editable&&<button className="secondary" onClick={()=>setOpen(true)}>Choose template & details</button>}<button onClick={()=>printElement(printRef.current,`${report.student.name} report card`)}>Print / Save PDF</button></div>
   <header><BrandImage src={report.school.logoPath?'/api/assets/'+report.school.logoPath:''} name={report.school.schoolName} className="report-school-logo"/><div><h1>{report.school.schoolName}</h1><p>{report.school.tagline}</p><small>{report.school.address}<br/>{report.school.contactEmail} {report.school.contactPhone}</small></div>{report.student.profilePictureId&&<OptionalImage className="report-student-photo" src={'/api/files/'+report.student.profilePictureId} alt="Student"/>}</header>
   <h2>{report.term.name} pupil’s performance report</h2><div className="template-label">{template.name}</div>
   <div className="report-meta"><strong>{report.student.name}</strong><span>Class: {report.student.className}</span><span>Session: {report.term.session}</span>{meta.admissionNumber&&<span>Admission no: {meta.admissionNumber}</span>}{meta.gender&&<span>Gender: {meta.gender}</span>}{meta.age&&<span>Age: {meta.age}</span>}{meta.dateOfBirth&&<span>D.O.B: {meta.dateOfBirth}</span>}{meta.heightCm&&<span>Height: {meta.heightCm} cm</span>}{meta.weightKg&&<span>Weight: {meta.weightKg} kg</span>}{meta.house&&<span>House: {meta.house}</span>}{meta.clubSociety&&<span>Club / society: {meta.clubSociety}</span>}</div>
   <div className="report-body-grid"><section className="cognitive-domain"><h3>Cognitive domain</h3><table><thead><tr><th>Subject</th>{componentKeys.map(k=><th key={k}>{titleCase(k)}</th>)}<th>Total</th><th>Grade</th><th>Position</th><th>Remark</th><th>Class avg.</th></tr></thead><tbody>{report.subjects.map(s=><tr key={s.subjectId}><td>{s.subject}{s.core?' *':''}</td>{componentKeys.map(k=>{const entries=s.entries.filter(e=>e.componentKey===k);return <td key={k}>{entries.length?Math.round(entries.reduce((sum,e)=>sum+e.score/e.maxScore*100,0)/entries.length):'—'}</td>})}<td>{s.total}%</td><td>{s.grade}</td><td>{s.rank}/{s.classSize}</td><td>{s.remark}</td><td>{s.classAverage}%</td></tr>)}</tbody></table></section>
    <aside className="report-side"><section><h3>Attendance summary</h3><p>Times present <b>{report.attendance.present}</b></p><p>Times absent <b>{report.attendance.absent}</b></p><p>Times late <b>{report.attendance.late}</b></p><p>Records <b>{report.attendance.total}</b></p></section><RatingTable title="Affective domain" items={affective} values={settings.affectiveRatings||{}}/><RatingTable title="Psychomotor skills" items={psychomotor} values={settings.psychomotorRatings||{}}/><RatingTable title="Extra activities" items={extraActivities} values={extra}/></aside>
   </div>
   <div className="report-summary"><section><h3>Performance summary</h3><p>Total obtained <b>{report.totalObtained}</b></p><p>Total obtainable <b>{report.totalObtainable}</b></p><p>Percentage <b>{report.average}%</b></p><p>Overall grade <b>{report.overallGrade}</b></p><p>Position <b>{report.position}/{report.classSize}</b></p><p>Remark <b>{report.overallRemark}</b></p></section><section><h3>Grade analysis</h3>{Object.entries(report.gradeAnalysis).map(([grade,count])=><p key={grade}>{grade}<b>{count}</b></p>)}</section><section><h3>Grade scale</h3>{report.school.gradingScale.map(g=><p key={g.grade}><b>{g.grade}</b><span>{g.min}%+ · {g.remark}</span></p>)}</section></div>
   <section className="rating-key"><b>Conduct rating key:</b> 5 – Excellent · 4 – Very good · 3 – Good · 2 – Needs improvement · 1 – Poor</section>
   <div className="report-comments"><p><b>Class teacher’s remark:</b> {settings.teacherComment||'—'} <span>{meta.teacherName}</span></p><p><b>Principal’s remark:</b> {settings.principalComment||'—'}</p></div>
   <footer>{meta.promotionStatus&&<strong>Status: {meta.promotionStatus}</strong>}{meta.nextTermBegins&&<span>Next term begins: {meta.nextTermBegins}</span>}<div className="signature"><OptionalImage src={report.school.principalSignaturePath?'/api/files/'+report.school.principalSignaturePath:''} alt="Principal signature" fallback={<small>Signature image unavailable</small>}/><span>{report.school.principalName||'Principal'}<br/>Principal’s signature</span></div></footer>
  </article>
  <Modal title="Report card template and details" open={editable&&open} onClose={()=>setOpen(false)} wide><form className="report-settings-form" onSubmit={save}><section><h3>Choose a report template</h3><div className="template-picker">{reportTemplates.map(t=><label key={t.key}><input type="radio" name="templateKey" value={t.key} defaultChecked={settings.templateKey===t.key}/><span><b>{t.name}</b><small>{t.description}</small></span></label>)}</div></section><section className="form-grid"><h3>Learner details</h3>{Object.entries(metadataFields).map(([key,label])=><label key={key}>{label}<input name={key} defaultValue={meta[key]||''}/></label>)}</section><section><h3>Affective domain</h3><div className="rating-form-grid">{Object.entries(affective).map(([key,label])=><label key={key}>{label}<select name={'affective_'+key} defaultValue={settings.affectiveRatings?.[key]||3}>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n}</option>)}</select></label>)}</div></section><section><h3>Psychomotor skills</h3><div className="rating-form-grid">{Object.entries(psychomotor).map(([key,label])=><label key={key}>{label}<select name={'psychomotor_'+key} defaultValue={settings.psychomotorRatings?.[key]||3}>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n}</option>)}</select></label>)}</div></section><section className="form-grid"><label>Teacher comment<textarea name="teacherComment" defaultValue={settings.teacherComment}/></label><label>Principal comment<textarea name="principalComment" defaultValue={settings.principalComment}/></label></section><label className="check"><input name="published" type="checkbox" defaultChecked={settings.published}/>Publish this report to the learner</label><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button>Save report settings</button></div></form></Modal>
 </>;
}
