import React,{useEffect,useState} from 'react';
import {api} from './api';

const days=['','Monday','Tuesday','Wednesday','Thursday','Friday'];
const today=()=>new Date().toISOString().slice(0,10);

export function StaffAttendancePage({user,run}){
  const [date,setDate]=useState(today()),[rows,setRows]=useState([]),[note,setNote]=useState('');
  const load=()=>api('/academics/staff-attendance?date='+date).then(setRows);
  useEffect(()=>{load().catch(()=>{})},[date]);
  const mine=rows.find(row=>row.staffId===user.id);
  return <div className="operations-page"><section className="panel operations-hero"><div><span className="eyebrow">DAILY RESUMPTION</span><h2>Staff attendance</h2><p>Staff record arrival once per working day. Administrators can review the complete daily register.</p></div><label>Attendance date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></section>{user.role==='STAFF'&&<section className="panel attendance-checkin"><div><h2>{mine?'Attendance recorded':'Mark today’s resumption'}</h2><p>{mine?`Marked ${mine.status.toLowerCase()} at ${new Date(mine.markedAt).toLocaleTimeString()}`:'Choose your arrival status. The current time is recorded automatically.'}</p></div><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Optional note" maxLength="300"/><button onClick={()=>run(async()=>{await api('/academics/staff-attendance/self',{method:'POST',body:{status:'PRESENT',note}});await load()},'Attendance marked')}>Mark present</button><button className="secondary" onClick={()=>run(async()=>{await api('/academics/staff-attendance/self',{method:'POST',body:{status:'LATE',note}});await load()},'Late arrival recorded')}>Mark late</button></section>}<section className="panel table-wrap"><div className="panel-title"><h2>Daily register</h2><span className="badge">{rows.length} staff</span></div><table><thead><tr><th>Staff member</th><th>Status</th><th>Time</th><th>Note</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.staff.name}</strong><small>{row.staff.email}</small></td><td><span className="badge submitted">{row.status}</span></td><td>{new Date(row.markedAt).toLocaleTimeString()}</td><td>{row.note||'—'}</td></tr>)}</tbody></table>{!rows.length&&<p className="empty">No staff attendance has been recorded for this date.</p>}</section></div>;
}

export function TimetablePage({user,classes,run}){
  const [rows,setRows]=useState([]),[catalog,setCatalog]=useState({subjects:[],teachers:[]}),[open,setOpen]=useState(false);
  const load=()=>Promise.all([api('/academics/timetable').then(setRows),api('/academics/catalog').then(setCatalog)]);
  useEffect(()=>{load().catch(()=>{})},[]);
  const availableClasses=classes.length?classes:catalog.courses.map(course=>course.class).filter((item,index,items)=>items.findIndex(x=>x.id===item.id)===index);
  const submit=e=>{e.preventDefault();const form=e.currentTarget,d=new FormData(form);run(async()=>{await api('/academics/timetable',{method:'POST',body:{classId:d.get('classId'),subjectId:d.get('subjectId'),teacherId:d.get('teacherId')||undefined,dayOfWeek:Number(d.get('dayOfWeek')),startsAt:d.get('startsAt'),endsAt:d.get('endsAt'),room:d.get('room')}});form.reset();setOpen(false);await load()},'Timetable period created')};
  return <div className="operations-page"><div className="toolbar"><div><span className="eyebrow">WEEKLY PLAN</span><h2>School timetable</h2></div><button onClick={()=>setOpen(!open)}>{open?'Close form':'+ Add period'}</button></div>{open&&<section className="panel"><form className="form-grid" onSubmit={submit}><label>Class<select name="classId" required><option value="">Choose class</option>{availableClasses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Subject<select name="subjectId" required><option value="">Choose subject</option>{catalog.subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{user.role==='ADMIN'&&<label>Teacher<select name="teacherId" required><option value="">Choose teacher</option>{catalog.teachers.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}<label>Day<select name="dayOfWeek" required>{days.slice(1).map((day,index)=><option value={index+1} key={day}>{day}</option>)}</select></label><label>Starts<input name="startsAt" type="time" required/></label><label>Ends<input name="endsAt" type="time" required/></label><label>Room / location<input name="room" maxLength="80" placeholder="e.g. Room 12"/></label><button>Create period</button></form></section>}<div className="timetable-board">{days.slice(1).map((day,index)=><section className="panel timetable-day" key={day}><h3>{day}</h3>{rows.filter(row=>row.dayOfWeek===index+1).map(row=><article key={row.id}><time>{row.startsAt} – {row.endsAt}</time><strong>{row.subject.name}</strong><span>{row.class.name} · {row.teacher.name}</span><small>{row.room||'Room not specified'}</small><button className="text-button" onClick={()=>run(async()=>{await api('/academics/timetable/'+row.id,{method:'DELETE'});await load()},'Period removed')}>Remove</button></article>)}{!rows.some(row=>row.dayOfWeek===index+1)&&<p className="empty">No periods</p>}</section>)}</div></div>;
}
