import React,{useEffect,useState} from 'react';
import {api,uploadFile} from './api';
import {BrandImage,OptionalImage} from './BrandImage';

export const permissions=['CLASSES_MANAGE','STUDENTS_MANAGE','STAFF_MANAGE','EXAMS_MANAGE','EXAMS_MONITOR','ASSIGNMENTS_MANAGE','MATERIALS_MANAGE','LIBRARY_MANAGE','HOSTEL_MANAGE','GRADES_MANAGE','RATINGS_MANAGE','REPORTS_VIEW','PROMOTIONS_MANAGE','RESULTS_VIEW','ATTENDANCE_MANAGE','PAYMENTS_MANAGE','COMMUNICATIONS_MANAGE','SYNC_VIEW','AUDIT_VIEW','SETTINGS_MANAGE'];
const human=value=>String(value).toLowerCase().replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const Field=({title,children})=><label>{title}{children}</label>;
export const Search=({value,onChange,placeholder='Search records',count})=><label className="search-box search-box-v4"><svg className="search-icon" aria-hidden="true" viewBox="0 0 24 24"><circle cx="11" cy="11" r="6"/><path d="m16 16 4 4"/></svg><input aria-label={placeholder} type="search" value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>{value&&<button type="button" aria-label="Clear search" onClick={()=>onChange('')}>×</button>}{Number.isFinite(count)&&<span className="search-count">{count}</span>}</label>;
export function Modal({title,open,onClose,children,wide=false}){
 if(!open)return null;
 return <div className="modal-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className={'modal-card '+(wide?'wide':'')} role="dialog" aria-modal="true" aria-label={title}><header><div><span className="eyebrow">SCHOOLHOUSE</span><h2>{title}</h2></div><button type="button" className="icon-button" aria-label="Close" onClick={onClose}>×</button></header>{children}</section></div>;
}
function PermissionChecks({selected=[]}){return <div className="permission-grid">{permissions.map(p=><label className="check" key={p}><input type="checkbox" name="permissions" value={p} defaultChecked={selected.includes(p)}/>{human(p)}</label>)}</div>}

export function StaffManager({staff,roles,classes,busy,run}){
 const [dialog,setDialog]=useState(null),[selected,setSelected]=useState(null),[query,setQuery]=useState('');
 const q=query.toLowerCase(),shown=staff.filter(s=>[s.name,s.email,s.staffProfile?.employeeNumber,s.staffRole?.name].some(v=>String(v||'').toLowerCase().includes(q)));
 const createStaff=e=>{e.preventDefault();const f=e.currentTarget,d=new FormData(f);run(async()=>{await api('/admin/staff',{method:'POST',body:{name:d.get('name'),email:d.get('email'),password:d.get('password'),staffRoleId:d.get('staffRoleId'),employeeNumber:d.get('employeeNumber'),phone:d.get('phone'),address:d.get('address'),qualifications:d.get('qualifications').split(',').map(x=>x.trim()).filter(Boolean),salaryMinor:d.get('salary')?Math.round(Number(d.get('salary'))*100):null,payrollStatus:d.get('payrollStatus'),classIds:d.getAll('classIds')}});setDialog(null)},'Staff account and profile created')};
 const createRole=e=>{e.preventDefault();const d=new FormData(e.currentTarget);run(async()=>{await api('/admin/staff-roles',{method:'POST',body:{name:d.get('name'),description:d.get('description'),permissions:d.getAll('permissions')}});setDialog(null)},'Staff role created')};
 const saveRole=e=>{e.preventDefault();const d=new FormData(e.currentTarget);run(async()=>{await api('/admin/staff-roles/'+selected.id,{method:'PUT',body:{name:d.get('name'),description:d.get('description'),permissions:d.getAll('permissions')}});setDialog(null)},'Role updated; affected staff must sign in again')};
 const saveClasses=e=>{e.preventDefault();const d=new FormData(e.currentTarget);run(async()=>{await api('/admin/staff/'+selected.id,{method:'PATCH',body:{classIds:d.getAll('classIds')}});setDialog(null)},'Teacher class assignments updated')};
 return <><div className="toolbar"><Search value={query} onChange={setQuery} placeholder="Search staff, role or employee number"/><button onClick={()=>setDialog('staff')}>+ Add staff</button><button className="secondary" onClick={()=>setDialog('role')}>+ Create role</button></div>
 <section className="panel table-wrap"><div className="panel-title"><h2>Staff directory</h2><span className="muted">{shown.length} of {staff.length}</span></div><table><thead><tr><th>Staff member</th><th>Role</th><th>Profile</th><th>Status</th><th>Actions</th></tr></thead><tbody>{shown.map(s=><tr key={s.id}><td><strong>{s.name}</strong><small>{s.email}<br/>{s.staffProfile?.employeeNumber||'Profile pending'}</small></td><td>{s.staffRole?.name||'Unassigned'}</td><td>{human(s.staffProfile?.payrollStatus||'NOT_CONFIGURED')}<small>{s.staffClasses?.length||0} classes · {s.teachingAssignments?.length||0} courses</small></td><td><span className="badge">{s.active?'Active':'Disabled'}</span></td><td className="row-actions"><button className="text-button" onClick={()=>{setSelected(s);setDialog('classes')}}>Assign as class teacher</button><button className="text-button" onClick={()=>run(()=>api('/admin/staff/'+s.id,{method:'PATCH',body:{active:!s.active}}))}>{s.active?'Disable':'Enable'}</button><button className="text-button" onClick={()=>{setSelected(s);setDialog('password')}}>Reset credentials</button></td></tr>)}</tbody></table>{!shown.length&&<p className="empty">No staff match your search.</p>}</section>
 <section className="panel"><div className="panel-title"><h2>Roles and permissions</h2><span className="muted">{roles.length} roles</span></div><div className="cards compact-cards">{roles.filter(r=>!q||r.name.toLowerCase().includes(q)).map(role=><article className="role-card" key={role.id}><div><strong>{role.name}</strong><small>{role.description||'No description'} · {role._count?.users||0} staff</small></div><button className="secondary" onClick={()=>{setSelected(role);setDialog('editRole')}}>Edit permissions</button></article>)}</div></section>
 <Modal title="Add staff member" open={dialog==='staff'} onClose={()=>setDialog(null)} wide><form className="form-grid" onSubmit={createStaff}><Field title="Full name"><input name="name" required/></Field><Field title="Email / login"><input name="email" type="email" required/></Field><Field title="Initial password"><input name="password" type="password" minLength={12} maxLength={72} required/></Field><Field title="Employee number"><input name="employeeNumber" required/></Field><Field title="Phone"><input name="phone"/></Field><Field title="Address"><input name="address"/></Field><Field title="Qualifications (comma separated)"><input name="qualifications"/></Field><Field title="Monthly salary"><input name="salary" type="number" min="0" step=".01"/></Field><Field title="Payroll status"><select name="payrollStatus"><option value="NOT_CONFIGURED">Not configured</option><option value="ACTIVE">Active</option><option value="SUSPENDED">Suspended</option></select></Field><Field title="Staff role"><select name="staffRoleId" required><option value="">Select role</option>{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></Field><fieldset><legend>Assigned classes</legend>{classes.map(c=><label className="check" key={c.id}><input name="classIds" type="checkbox" value={c.id}/>{c.name}</label>)}</fieldset><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setDialog(null)}>Cancel</button><button disabled={busy}>Create staff account</button></div></form></Modal>
 <Modal title="Create staff role" open={dialog==='role'} onClose={()=>setDialog(null)} wide><form onSubmit={createRole}><div className="form-grid"><Field title="Role name"><input name="name" required/></Field><Field title="Description"><input name="description"/></Field></div><PermissionChecks/><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setDialog(null)}>Cancel</button><button disabled={busy}>Create role</button></div></form></Modal>
 <Modal title={'Edit '+(selected?.name||'role')} open={dialog==='editRole'} onClose={()=>setDialog(null)} wide>{dialog==='editRole'&&selected&&<form onSubmit={saveRole}><div className="form-grid"><Field title="Role name"><input name="name" defaultValue={selected.name} required/></Field><Field title="Description"><input name="description" defaultValue={selected.description}/></Field></div><PermissionChecks selected={(selected.grants||[]).map(g=>g.permission)}/><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setDialog(null)}>Cancel</button><button disabled={busy}>Save permissions</button></div></form>}</Modal>
 <Modal title="Reset staff credentials" open={dialog==='password'} onClose={()=>setDialog(null)}><form onSubmit={e=>{e.preventDefault();const password=new FormData(e.currentTarget).get('password');run(async()=>{await api('/admin/staff/'+selected.id,{method:'PATCH',body:{password}});setDialog(null)},'Credentials reset')}}><p>Set a new password for <strong>{selected?.name}</strong>.</p><Field title="New password"><input name="password" type="password" minLength="12" maxLength="128" autoComplete="new-password" required/></Field><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setDialog(null)}>Cancel</button><button disabled={busy}>Reset credentials</button></div></form></Modal>
 <Modal title={'Assign class teacher duties to '+(selected?.name||'teacher')} open={dialog==='classes'} onClose={()=>setDialog(null)}>{selected&&<form onSubmit={saveClasses}><p className="muted">Selected classes will show this staff member as class teacher and grant class-management access.</p>{classes.map(c=><label className="check" key={c.id}><input name="classIds" type="checkbox" value={c.id} defaultChecked={selected.staffClasses?.some(x=>x.classId===c.id)||c.classTeacher?.id===selected.id}/>{c.name}</label>)}<div className="modal-actions"><button type="button" className="secondary" onClick={()=>setDialog(null)}>Cancel</button><button disabled={busy}>Save class teacher assignment</button></div></form>}</Modal></>;
}

const settingsKeys=['schoolName','shortName','tagline','primaryColor','accentColor','academicYear','currentTerm','defaultCurrency','locale','timeZone','autosaveSeconds','kioskFullscreen','logoPath','watermarkPath','address','contactEmail','contactPhone','gradingScale','passingMark','syncEnabled','hostelEnabled','activeSessionId','activeTermId','principalName','principalSignaturePath'];
const settingDefaults={logoPath:'',watermarkPath:'',address:'',contactEmail:'',contactPhone:'',principalName:'',principalSignaturePath:'',activeSessionId:null,activeTermId:null,gradingScale:[],hostelEnabled:false};
const cleanSettings=s=>Object.fromEntries(settingsKeys.map(k=>[k,s[k]??(Object.hasOwn(settingDefaults,k)?settingDefaults[k]:'')]));
export function SettingsPanel({section,settings,save,busy}){
 const [sessions,setSessions]=useState([]),[open,setOpen]=useState(false);
 useEffect(()=>{if(section==='Configuration')api('/academics/catalog').then(x=>setSessions(x.sessions)).catch(()=>{})},[section]);
 const openSettings=()=>setOpen(true);
 const submit=async e=>{e.preventDefault();const d=new FormData(e.currentTarget),body=cleanSettings(settings);
  if(section==='Personalization'){for(const k of ['schoolName','shortName','tagline','primaryColor','accentColor','address','contactEmail','contactPhone','principalName'])body[k]=d.get(k);for(const key of ['logoPath','watermarkPath','principalSignaturePath']){const f=d.get(key);if(f?.size)body[key]=(await uploadFile(f,'branding')).id}}
  if(section==='Configuration'){for(const k of ['academicYear','currentTerm','defaultCurrency','locale','timeZone'])body[k]=d.get(k);body.autosaveSeconds=Number(d.get('autosaveSeconds'));body.passingMark=Number(d.get('passingMark'));body.kioskFullscreen=d.get('kioskFullscreen')==='on';body.syncEnabled=d.get('syncEnabled')==='on';body.hostelEnabled=d.get('hostelEnabled')==='on';body.activeSessionId=d.get('activeSessionId')||null;body.activeTermId=d.get('activeTermId')||null;body.gradingScale=d.get('gradingScale').split('\n').filter(Boolean).map(line=>{const [grade,min,...remark]=line.split(',');return{grade:grade.trim(),min:Number(min),remark:remark.join(',').trim()}})}
  await save(body);setOpen(false);
 };
 const title=section==='Personalization'?'School identity and report branding':'System configuration';
 return <><section className="panel settings-summary"><div><span className="eyebrow">CURRENT SETTINGS</span><h2>{title}</h2><p className="muted">{section==='Personalization'?settings.schoolName+' · '+(settings.address||'Address not set'):(settings.academicYear||'Academic year not set')+' · '+(settings.currentTerm||'Term not set')}</p></div><button onClick={openSettings}>Edit settings</button></section>
 {section==='Configuration'&&<><FeatureStatus features={settings.features}/><Definitions/></>}
 {section==='Personalization'&&<section className="panel branding-preview"><div><span className="eyebrow">CURRENT BRANDING</span><h2>Uploaded school assets</h2><p className="muted">A placeholder or unavailable label means the stored image file must be uploaded again.</p></div><article><BrandImage src={settings.logoPath?'/api/assets/'+settings.logoPath:''} name={settings.schoolName} className="branding-sample"/><strong>School logo</strong></article><article>{settings.watermarkPath?<OptionalImage src={'/api/assets/'+settings.watermarkPath} className="branding-sample" alt="Report watermark" fallback={<span className="branding-missing">Unavailable</span>}/>:<span className="branding-missing">Not set</span>}<strong>Watermark</strong></article><article>{settings.principalSignaturePath?<OptionalImage src={'/api/files/'+settings.principalSignaturePath} className="branding-sample signature-sample" alt="Principal signature" fallback={<span className="branding-missing">Unavailable</span>}/>:<span className="branding-missing">Not set</span>}<strong>Signature</strong></article></section>}
 <Modal title={title} open={open} onClose={()=>setOpen(false)} wide><form onSubmit={submit}>
 {section==='Personalization'&&<div className="form-grid"><Field title="School name"><input name="schoolName" defaultValue={settings.schoolName} required/></Field><Field title="Short name"><input name="shortName" defaultValue={settings.shortName} maxLength={12} required/></Field><Field title="Tagline"><input name="tagline" defaultValue={settings.tagline}/></Field><Field title="Address"><input name="address" defaultValue={settings.address}/></Field><Field title="Contact email"><input name="contactEmail" type="email" defaultValue={settings.contactEmail}/></Field><Field title="Contact phone"><input name="contactPhone" defaultValue={settings.contactPhone}/></Field><Field title="Principal name"><input name="principalName" defaultValue={settings.principalName}/></Field><Field title="Primary color"><input name="primaryColor" type="color" defaultValue={settings.primaryColor}/></Field><Field title="Accent color"><input name="accentColor" type="color" defaultValue={settings.accentColor}/></Field><Field title="School logo"><input name="logoPath" type="file" accept=".png,.jpg,.jpeg"/></Field><Field title="Report watermark"><input name="watermarkPath" type="file" accept=".png,.jpg,.jpeg"/></Field><Field title="Principal signature"><input name="principalSignaturePath" type="file" accept=".png,.jpg,.jpeg"/></Field></div>}
 {section==='Configuration'&&<><div className="form-grid"><Field title="Academic year"><input name="academicYear" defaultValue={settings.academicYear}/></Field><Field title="Current term label"><input name="currentTerm" defaultValue={settings.currentTerm}/></Field><Field title="Default currency"><input name="defaultCurrency" defaultValue={settings.defaultCurrency} pattern="[A-Z]{3}" maxLength={3}/></Field><Field title="Locale"><input name="locale" defaultValue={settings.locale}/></Field><Field title="Time zone"><input name="timeZone" defaultValue={settings.timeZone}/></Field><Field title="Autosave seconds"><input name="autosaveSeconds" type="number" min={3} max={30} defaultValue={settings.autosaveSeconds}/></Field><Field title="Default passing mark"><input name="passingMark" type="number" min="0" max="100" defaultValue={settings.passingMark}/></Field><Field title="Active academic session"><select name="activeSessionId" defaultValue={settings.activeSessionId||''}><option value="">Not selected</option>{sessions.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field title="Active term"><select name="activeTermId" defaultValue={settings.activeTermId||''}><option value="">Not selected</option>{sessions.flatMap(s=>s.terms.map(t=><option key={t.id} value={t.id}>{s.name} · {t.name}</option>))}</select></Field></div><Field title="Grading scale (Grade, minimum, remark — one per line)"><textarea name="gradingScale" defaultValue={(settings.gradingScale||[]).map(g=>`${g.grade},${g.min},${g.remark}`).join('\n')}/></Field><label className="check"><input name="kioskFullscreen" type="checkbox" defaultChecked={settings.kioskFullscreen}/>Require fullscreen during student exams</label><label className="check"><input name="syncEnabled" type="checkbox" defaultChecked={settings.syncEnabled}/>Enable periodic cloud synchronization</label><label className="check"><input name="hostelEnabled" type="checkbox" defaultChecked={settings.hostelEnabled}/>Enable hostel management module</label></>}
 <div className="modal-actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button disabled={busy}>Save settings</button></div></form></Modal></>;
}
function FeatureStatus({features={}}){const labels={cbt:'CBT tests',assignments:'Assignments',library:'Library',attendance:'Attendance',reports:'Reports and promotions',hostel:'Hostels',payments:'Payments',communications:'Mailing and SMS',email:'Email delivery',sms:'SMS delivery',cloudSync:'Cloud sync'};return <section className="panel"><div className="panel-title"><div><span className="eyebrow">SERVER FEATURE CONTROLS</span><h2>Available modules</h2></div><small>Edit config/features.json, then restart the server</small></div><div className="feature-status-grid">{Object.entries(labels).map(([key,label])=><article key={key}><span className={features[key]===false?'status-dot off':'status-dot'}/><strong>{label}</strong><small>{features[key]===false?'Disabled by server':'Available'}</small></article>)}</div></section>}
function Definitions(){const items=[['Academic session','The full school year, such as 2026/2027. It contains one or more terms.'],['Term','A teaching and reporting period inside a session, such as First Term.'],['Class','A student group or grade level, such as JSS 1A.'],['Subject','A curriculum area, such as Mathematics or English.'],['Course','A subject taught to one class. A course links the class, subject, teacher and grading rubric.'],['Rubric','The percentage weights used to combine assessments, assignments and final exams.'],['Passing mark','The default minimum percentage considered a pass.'],['Active session and term','The periods currently used for new records, reports and day-to-day work.']];return <section className="panel"><h2>School setup terms</h2><div className="definition-grid">{items.map(([term,text])=><article key={term}><strong>{term}</strong><p>{text}</p></article>)}</div></section>}
