import React from 'react';
const actions=[['STUDENTS_MANAGE','♙','Manage assigned students','Students'],['ATTENDANCE_MANAGE','✓','Take class attendance','Attendance'],['EXAMS_MANAGE','▧','Create a CBT test','CBT Tests'],['GRADES_MANAGE','▦','Record and review grades','Overall grading'],['RATINGS_MANAGE','☆','Rate student development','Student ratings'],['ASSIGNMENTS_MANAGE','✎','Post an assignment','Assignments'],['REPORTS_VIEW','▥','Prepare report cards','Report cards'],['LIBRARY_MANAGE','▤','Publish library material','Library'],['HOSTEL_MANAGE','⌂','Manage hostel residents','Hostels'],['COMMUNICATIONS_MANAGE','✉','Message students and guardians','Communications']];
const moduleFor={Attendance:'attendance','CBT Tests':'cbt',Results:'cbt',Assignments:'assignments',Library:'library',Hostels:'hostel','Report cards':'reports','Student ratings':'reports',Communications:'communications'};
export function StaffDashboard({user,classes,students,exams,monitor,results,setPage,hostelEnabled,features={}}){
  const can=p=>user.permissions?.includes(p),enabled=target=>features[moduleFor[target]]!==false;
  const available=actions.filter(a=>can(a[0])&&enabled(a[3])&&(a[3]!=='Hostels'||hostelEnabled));
  const stats=[['Assigned classes',classes.length,'Classes','CLASSES_MANAGE'],['Visible students',students.length,'Students','STUDENTS_MANAGE'],['CBT tests',exams.length,'CBT Tests','EXAMS_MANAGE'],['Results',results.length,'Results','RESULTS_VIEW']].filter(x=>can(x[3])&&enabled(x[2]));
  return <div className="staff-dashboard"><section className="staff-hero"><div><span className="eyebrow">STAFF WORKSPACE</span><h2>Welcome, {user.name?.split(' ')[0]}.</h2><p>Your dashboard shows only the classes, courses and tools assigned through the <strong>{user.staffRole?.name||'staff'}</strong> role.</p></div><div className="staff-role-card"><small>YOUR ROLE</small><strong>{user.staffRole?.name||'Staff'}</strong><span>{user.permissions?.length||0} permissions</span></div></section><div className="dashboard-stats">{stats.map(([label,value,target])=><button className="dashboard-stat" key={label} onClick={()=>setPage(target)}><span>{label}</span><strong>{value}</strong><b>Open →</b></button>)}</div><section className="panel"><div className="panel-title"><div><span className="eyebrow">AUTHORIZED WORK</span><h2>Role-based tools</h2></div><span className="badge">{available.length} available</span></div><div className="staff-action-grid">{available.map(([permission,icon,label,target])=><button key={permission} onClick={()=>setPage(target)}><span>{icon}</span><strong>{label}</strong><small>{permission.replaceAll('_',' ').toLowerCase()}</small></button>)}</div></section><div className="dashboard-grid"><section className="panel"><h2>Assigned classes</h2>{classes.map(c=><div className="list-row" key={c.id}><strong>{c.name}</strong><span>{c._count.students} students</span></div>)}{!classes.length&&<p className="empty">No classes or courses are assigned to this account.</p>}</section>{features.cbt!==false&&<section className="panel"><h2>Live assessment activity</h2><p><strong>{monitor.filter(x=>x.status==='ACTIVE').length}</strong> active CBT sessions</p><p><strong>{results.length}</strong> submitted results visible to your role</p></section>}</div></div>;
}
