import React,{useEffect,useMemo,useState} from 'react';
import {api} from './api';
import {Modal} from './StaffSettings';
const tabs=['Profile','Performance','Activities & ratings','Medical information'];
const ageOf=date=>date?Math.max(0,Math.floor((Date.now()-new Date(date))/(365.2425*86400000))):'—';
const dateValue=value=>value?new Date(value).toISOString().slice(0,10):'';
export function StudentProfile({studentId,classes,run,onClose,onUpdated}){
 const [data,setData]=useState(null),[tab,setTab]=useState('Profile'),[editing,setEditing]=useState(false),[error,setError]=useState('');
 const load=()=>api('/admin/students/'+studentId+'/profile').then(setData).catch(e=>setError(e.message));
 useEffect(()=>{load()},[studentId]);
 const chart=useMemo(()=>{if(!data)return[];const grouped={};for(const g of data.gradeEntries){const name=g.classSubject.subject.name;(grouped[name]||=[]).push(g.score/g.maxScore*100)}return Object.entries(grouped).map(([subject,scores])=>({subject,value:Math.round(scores.reduce((a,b)=>a+b,0)/scores.length)})).sort((a,b)=>b.value-a.value)},[data]);
 const save=e=>{e.preventDefault();const d=new FormData(e.currentTarget),body=Object.fromEntries(['name','email','classId','phone','address','dateOfBirth','gender','emergencyContactName','emergencyContactPhone','emergencyRelationship','guardianEmail','medicalInformation'].map(k=>[k,d.get(k)]));for(const key of ['studentAllowEmail','studentAllowSms','guardianAllowEmail','guardianAllowSms'])body[key]=d.has(key);body.dateOfBirth=body.dateOfBirth||null;run(async()=>{await api('/admin/students/'+studentId,{method:'PATCH',body});setEditing(false);await load();await onUpdated?.()},'Student profile updated')};
 if(error)return <section className="student-profile-page"><button className="profile-back" onClick={onClose}>← Back to students</button><div className="error">{error}</div></section>;
 if(!data)return <section className="student-profile-page"><button className="profile-back" onClick={onClose}>← Back to students</button><div className="loading-panel">Loading student profile…</div></section>;
 return <section className="student-profile-page">
  <div className="profile-page-nav"><button className="profile-back" onClick={onClose}>← Back to students</button><span>Student record</span></div>
  <header className="student-profile-head profile-page-head">{data.profilePictureId?<img src={'/api/files/'+data.profilePictureId} alt=""/>:<span>{data.name[0]}</span>}<div><span className="eyebrow">LEARNER PROFILE</span><h2>{data.name}</h2><p>{data.class?.name||'No class'} · {data.active?'Active student':'Account disabled'}</p></div><button onClick={()=>setEditing(true)}>Edit student</button></header>
  <nav className="profile-tabs" role="tablist">{tabs.map(t=><button type="button" role="tab" aria-selected={tab===t} key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</nav>
  {tab==='Profile'&&<div className="profile-grid">{[['Full name',data.name],['Email',data.email],['Phone',data.phone||'—'],['Address',data.address||'—'],['Date of birth',data.dateOfBirth?new Date(data.dateOfBirth).toLocaleDateString():'—'],['Age',ageOf(data.dateOfBirth)],['Gender',data.gender||'—'],['Class',data.class?.name||'—'],['Class teacher',data.class?.classTeacher?.name||'—'],['Guardian / emergency contact',data.emergencyContactName||'—'],['Guardian phone',data.emergencyContactPhone||'—'],['Guardian email',data.guardianEmail||'—'],['Relationship',data.emergencyRelationship||'—'],['Student messages',`${data.studentAllowEmail?'Email on':'Email off'} · ${data.studentAllowSms?'SMS on':'SMS off'}`],['Guardian messages',`${data.guardianAllowEmail?'Email on':'Email off'} · ${data.guardianAllowSms?'SMS on':'SMS off'}`],['Last login',data.lastLoginAt?new Date(data.lastLoginAt).toLocaleString():'Never'],['Registered',new Date(data.createdAt).toLocaleDateString()]].map(([label,value])=><article key={label}><small>{label}</small><strong>{value}</strong></article>)}</div>}
  {tab==='Performance'&&<div className="profile-content-grid"><section className="panel"><div className="panel-title"><h2>Subject performance</h2><span className="muted">Average of recorded components</span></div><div className="performance-chart">{chart.map(x=><div key={x.subject}><span>{x.subject}</span><div><i style={{width:x.value+'%'}}/></div><b>{x.value}%</b></div>)}{!chart.length&&<p className="empty">No recorded subject scores yet.</p>}</div></section><section className="panel table-wrap"><h2>Score history</h2><table><thead><tr><th>Subject</th><th>Term</th><th>Component</th><th>Score</th></tr></thead><tbody>{data.gradeEntries.slice().reverse().map((g,i)=><tr key={i}><td>{g.classSubject.subject.name}</td><td>{g.term.session.name} · {g.term.name}</td><td>{g.componentKey.replaceAll('_',' ')}</td><td>{g.score}/{g.maxScore}</td></tr>)}</tbody></table></section></div>}
  {tab==='Activities & ratings'&&<div className="rating-history">{data.studentRatings.map(r=><article className="panel rating-history-card" key={r.id}><div className="panel-title"><h3>{r.category.replaceAll('_',' ')}</h3><span className="badge">{r.term.name}</span></div><p>{r.term.session.name}</p><div className="rating-chip-list">{Object.entries(r.ratings).map(([k,v])=><span key={k}>{k.replace(/([A-Z])/g,' $1')} <b>{v}/5</b></span>)}</div>{r.comment&&<p>{r.comment}</p>}<small>Rated by {r.ratedBy.name}</small></article>)}{!data.studentRatings.length&&<p className="empty">No affective, psychomotor or extra-activity ratings yet.</p>}</div>}
  {tab==='Medical information'&&<section className="medical-card"><span className="eyebrow">CONFIDENTIAL</span><h3>Medical information</h3><p>{data.medicalInformation||'No medical information has been recorded.'}</p><small>Available only to authorized school staff.</small></section>}
  <Modal title="Edit registered student" open={editing} onClose={()=>setEditing(false)} wide><form className="form-grid" onSubmit={save}><label>Full name<input name="name" defaultValue={data.name} required/></label><label>Email<input name="email" type="email" defaultValue={data.email} required/></label><label>Class<select name="classId" defaultValue={data.classId} required>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Date of birth<input name="dateOfBirth" type="date" defaultValue={dateValue(data.dateOfBirth)}/></label><label>Gender<input name="gender" defaultValue={data.gender}/></label><label>Phone<input name="phone" defaultValue={data.phone}/></label><label>Address<textarea name="address" defaultValue={data.address}/></label><label>Guardian / emergency contact<input name="emergencyContactName" defaultValue={data.emergencyContactName}/></label><label>Guardian phone<input name="emergencyContactPhone" defaultValue={data.emergencyContactPhone}/></label><label>Guardian email<input name="guardianEmail" type="email" defaultValue={data.guardianEmail}/></label><label>Relationship<input name="emergencyRelationship" defaultValue={data.emergencyRelationship}/></label><fieldset><legend>Communication preferences</legend><label className="check"><input name="studentAllowEmail" type="checkbox" defaultChecked={data.studentAllowEmail}/>Email student</label><label className="check"><input name="studentAllowSms" type="checkbox" defaultChecked={data.studentAllowSms}/>SMS student</label><label className="check"><input name="guardianAllowEmail" type="checkbox" defaultChecked={data.guardianAllowEmail}/>Email guardian</label><label className="check"><input name="guardianAllowSms" type="checkbox" defaultChecked={data.guardianAllowSms}/>SMS guardian</label></fieldset><label>Medical information<textarea name="medicalInformation" defaultValue={data.medicalInformation}/></label><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setEditing(false)}>Cancel</button><button>Save changes</button></div></form></Modal>
 </section>;
}
