import React,{useEffect,useMemo,useState} from 'react';
import {api} from './api';
import {Search} from './StaffSettings';
const groups={AFFECTIVE:{label:'Affective development',description:'Behaviour, responsibility and relationships',items:{attentiveness:'Attentiveness',honesty:'Honesty',neatness:'Neatness',politeness:'Politeness',punctuality:'Punctuality',selfControl:'Self control',obedience:'Obedience',reliability:'Reliability',responsibility:'Responsibility',relationshipWithOthers:'Relationship with others'}},PSYCHOMOTOR:{label:'Psychomotor skills',description:'Practical, communication and movement skills',items:{handlingOfTools:'Handling of tools',drawingPainting:'Drawing / painting',handwriting:'Handwriting',publicSpeaking:'Public speaking',speechFluency:'Speech fluency',sportsAndGames:'Sports and games'}},EXTRA_CURRICULAR:{label:'Activities and participation',description:'Sport, leadership and school-community participation',items:{sports:'Sports',leadership:'Leadership',teamwork:'Teamwork',creativity:'Creativity',music:'Music',clubs:'Clubs and societies',communityService:'Community service'}}};
const blank=()=>Object.fromEntries(Object.entries(groups).map(([category,group])=>[category,{ratings:Object.fromEntries(Object.keys(group.items).map(k=>[k,3])),comment:''}]));
const scale={5:'Excellent',4:'Very good',3:'Good',2:'Developing',1:'Needs support'};
export function StudentRatings({run}){
 const [catalog,setCatalog]=useState({sessions:[],students:[]}),[studentId,setStudentId]=useState(''),[termId,setTermId]=useState(''),[values,setValues]=useState(blank()),[query,setQuery]=useState(''),[active,setActive]=useState('AFFECTIVE');
 useEffect(()=>{api('/academics/catalog').then(setCatalog)},[]);
 useEffect(()=>{if(!studentId||!termId){setValues(blank());return}api(`/academics/ratings?studentId=${encodeURIComponent(studentId)}&termId=${encodeURIComponent(termId)}`).then(rows=>{const next=blank();for(const row of rows)next[row.category]={ratings:{...next[row.category].ratings,...row.ratings},comment:row.comment};setValues(next)})},[studentId,termId]);
 const terms=catalog.sessions.flatMap(s=>s.terms.map(t=>({...t,sessionName:s.name}))),students=(catalog.students||[]).filter(s=>!query||[s.name,s.class?.name].some(v=>String(v||'').toLowerCase().includes(query.toLowerCase()))),selected=catalog.students?.find(s=>s.id===studentId),group=groups[active];
 const average=category=>{const scores=Object.values(values[category].ratings);return scores.length?(scores.reduce((a,b)=>a+b,0)/scores.length).toFixed(1):'—'};
 const setRating=(category,key,value)=>setValues({...values,[category]:{...values[category],ratings:{...values[category].ratings,[key]:Number(value)}}});
 const save=()=>run(()=>api(`/academics/ratings/${studentId}/${termId}`,{method:'PUT',body:{categories:Object.entries(values).map(([category,data])=>({category,...data}))}}),'Student development ratings saved');
 return <div className="ratings-workspace">
  <section className="ratings-hero"><div><span className="eyebrow">WHOLE-CHILD ASSESSMENT</span><h2>Student development ratings</h2><p>Record conduct, practical skills, sports and extracurricular participation on one clear scale.</p></div><div className="rating-scale-key">{Object.entries(scale).reverse().map(([score,label])=><span key={score}><b>{score}</b>{label}</span>)}</div></section>
  <section className="panel rating-selector"><Search value={query} onChange={setQuery} placeholder="Search student or class" count={students.length}/><label>Student<select value={studentId} onChange={e=>setStudentId(e.target.value)}><option value="">Choose student</option>{students.map(s=><option value={s.id} key={s.id}>{s.name}{s.class?.name?' · '+s.class.name:''}</option>)}</select></label><label>Reporting term<select value={termId} onChange={e=>setTermId(e.target.value)}><option value="">Choose term</option>{terms.map(t=><option value={t.id} key={t.id}>{t.sessionName} · {t.name}</option>)}</select></label><button disabled={!studentId||!termId} onClick={save}>Save ratings</button></section>
  {studentId&&termId?<><section className="rating-student-strip"><div className="rating-student-avatar">{selected?.name?.[0]}</div><div><strong>{selected?.name}</strong><small>{selected?.class?.name||'Student'} · All changes save together</small></div>{Object.entries(groups).map(([key,g])=><button key={key} className={active===key?'active':''} onClick={()=>setActive(key)}><span>{g.label}</span><b>{average(key)}/5</b></button>)}</section><section className="panel rating-editor"><div className="rating-editor-head"><div><span className="eyebrow">CURRENT DOMAIN</span><h2>{group.label}</h2><p>{group.description}</p></div><div className="rating-average"><strong>{average(active)}</strong><small>average / 5</small></div></div><div className="rating-score-grid">{Object.entries(group.items).map(([key,label])=><article key={key}><div><strong>{label}</strong><small>{scale[values[active].ratings[key]]}</small></div><div className="score-buttons" role="radiogroup" aria-label={label}>{[1,2,3,4,5].map(n=><button type="button" role="radio" aria-checked={values[active].ratings[key]===n} className={values[active].ratings[key]===n?'selected':''} key={n} onClick={()=>setRating(active,key,n)}>{n}</button>)}</div></article>)}</div><label className="rating-comment">Domain comment<textarea value={values[active].comment} onChange={e=>setValues({...values,[active]:{...values[active],comment:e.target.value}})} placeholder="Optional observation or support note"/></label></section></>:<section className="panel rating-empty"><span>☆</span><h2>Choose a student and reporting term</h2><p>The rating domains and saved history will appear here.</p></section>}
 </div>;
}