import React,{useEffect,useState} from 'react';
import {api,uploadFile} from './api';
import ReportCard from './ReportCard';
export function StudentAcademics({user,features={},back}){
 const [assignments,setAssignments]=useState([]),[materials,setMaterials]=useState([]),[catalog,setCatalog]=useState({sessions:[]}),[report,setReport]=useState(null),[error,setError]=useState('');
 const enabled=key=>features[key]!==false;
 const load=()=>Promise.all([enabled('assignments')?api('/academics/assignments').then(setAssignments):Promise.resolve(),enabled('library')?api('/academics/materials').then(setMaterials):Promise.resolve(),api('/academics/catalog').then(setCatalog)]).catch(e=>setError(e.message));
 useEffect(()=>{load()},[]);
 const submit=async(e,a)=>{e.preventDefault();try{const d=new FormData(e.currentTarget);let fileIds=[];const f=d.get('file');if(f?.size)fileIds=[(await uploadFile(f,'submission')).id];await api('/academics/assignments/'+a.id+'/submit',{method:'POST',body:{text:d.get('text'),fileIds}});await load()}catch(x){setError(x.message)}};
 const terms=catalog.sessions.flatMap(s=>s.terms.map(t=>({...t,sessionName:s.name})));
 return <main className="student-academics"><button className="text-button" onClick={back}>← Examinations</button><h1>My learning</h1>{error&&<div className="error">{error}</div>}<div className="student-learning-grid">{enabled('assignments')&&<section><h2>Assignments</h2>{assignments.map(a=><article className="panel" key={a.id}><span className="badge">{a.submissions.length?'Submitted':'Open'}</span><h3>{a.title}</h3><p>{a.classSubject.subject.name}</p><small>Due {new Date(a.dueAt).toLocaleString()} · {a.maxScore} marks</small><p>{a.instructions}</p>{a.attachments.map(x=><a className="file-link" href={'/api/files/'+x.file.id} key={x.file.id}>{x.file.originalName}</a>)}<form onSubmit={e=>submit(e,a)}><textarea name="text" defaultValue={a.submissions[0]?.text} placeholder="Write your response or attach a file"/><input name="file" type="file" accept=".pdf,.png,.jpg,.jpeg,.txt"/><button>Submit assignment</button></form>{a.submissions[0]?.gradedAt&&<div className="success">Score: {a.submissions[0].score}/{a.maxScore} · {a.submissions[0].feedback}</div>}</article>)}</section>}{enabled('library')&&<section><h2>Study materials</h2>{materials.map(m=><article className="panel" key={m.id}><h3>{m.title}</h3><p>{m.classSubject.subject.name} · {m.description}</p><a className="file-link" href={'/api/files/'+m.file.id}>Download {m.file.originalName}</a></article>)}</section>}{enabled('reports')&&<section><section className="panel"><h2>My report card</h2><select onChange={e=>e.target.value&&api('/academics/reports/'+user.id+'/'+e.target.value).then(setReport).catch(x=>setError(x.message))}><option value="">Choose a term</option>{terms.map(t=><option value={t.id} key={t.id}>{t.sessionName} · {t.name}</option>)}</select></section></section>}</div>{report&&enabled('reports')&&<ReportCard report={report} editable={false} run={async fn=>{try{await fn()}catch(x){setError(x.message)}}}/>}</main>;
}
